Use :buster on Dockerfile
The jessie image no longer works for testing the current code base. I
think that commit 833b51bc7f9b66e3a705fe402091bbd10fba02ce introduced
the following error when running "make run":

   ImportError: cannot import name FlaskForm

The changes introduced in this commit make the debsources container
work. I was able to browse the test data through the web interface.